language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  - SYMFONY_VERSION=3.3.*

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.0.*
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.3
      env: SYMFONY_VERSION=4.0.*
    - php: 7.3
      env: SYMFONY_VERSION=4.1.*
    - php: 7.3
      env: SYMFONY_VERSION=4.2.*
    - php: 7.3
      env: SYMFONY_VERSION=4.3.*
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*

before_install:
  - sh -c 'if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
  - git config --global user.email "test@test.com"
  - git config --global user.name "John Doe"
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/console:${SYMFONY_VERSION}" "symfony/yaml:${SYMFONY_VERSION}" "symfony/process:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist $COMPOSER_FLAGS

script: bin/phpunit --coverage-text

notifications:
  slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
  email:
    - david.jeanmonod@liip.ch
    - laurent.prodon@liip.ch
