language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.5.*

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - php: 5.6
    - php: hhvm
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.0.*
    - php: 5.5
      env: SYMFONY_VERSION=2.1.*
    - php: 5.5
      env: SYMFONY_VERSION=2.2.*
    - php: 5.5
      env: SYMFONY_VERSION=2.3.*
    - php: 5.5
      env: SYMFONY_VERSION=2.4.*
    - php: 5.5
      env: SYMFONY_VERSION=dev-master

before_script:
  - git config --global user.email "test@test.com"
  - git config --global user.name "John Doe"
  - composer self-update
  - composer require symfony/console:${SYMFONY_VERSION} symfony/yaml:${SYMFONY_VERSION} symfony/process:${SYMFONY_VERSION} --no-update
  - composer update symfony/console symfony/yaml symfony/process

script: phpunit --coverage-text

notifications:
  slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
  email:
    - david.jeanmonod@liip.ch
    - laurent.prodon@liip.ch
