language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  include:
    - php: 8.0
      env: SYMFONY_VERSION=6.0.*
    - php: 8.0
      env: SYMFONY_VERSION=5.0.*
    - php: 8.0
      env: SYMFONY_VERSION=4.4.*
    - php: 7.4
      env: SYMFONY_VERSION=5.0.*
    - php: 7.4
      env: SYMFONY_VERSION=4.4.*
    - php: 7.4
      env: SYMFONY_VERSION=4.3.*
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*
    - php: 7.3
      env: SYMFONY_VERSION=4.3.*
    - php: 7.2
      env: SYMFONY_VERSION=4.2.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*

before_install:
  - sh -c 'echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini'
  - git config --global user.email "test@test.com"
  - git config --global user.name "John Doe"
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/console:${SYMFONY_VERSION}" "symfony/yaml:${SYMFONY_VERSION}" "symfony/process:${SYMFONY_VERSION}" --no-update; fi;

install:
  - composer update --prefer-dist $COMPOSER_FLAGS
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "8.0" ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-9.phar; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-8.phar; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-8.phar; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-8.phar; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit

script: phpunit --coverage-text

notifications:
  slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
  email:
    - david.jeanmonod@liip.ch
    - laurent.prodon@liip.ch
